# Generated by Django 3.2.20 on 2023-08-07 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=150, verbose_name='SKU')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название товара')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория товара')),
                ('vendor', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('barcode', models.CharField(blank=True, max_length=20, verbose_name='Первый баркод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Товар пользователя')),
            ],
            options={
                'verbose_name': 'Товар пользователя',
                'verbose_name_plural': 'Товары пользователей',
                'ordering': ['sku'],
            },
        ),
        migrations.AddConstraint(
            model_name='goods',
            constraint=models.UniqueConstraint(fields=('sku',), name='unique sku'),
        ),
    ]
