# Generated by Django 3.2.20 on 2023-08-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория товара'),
        ),
    ]
