# Generated by Django 3.2.20 on 2023-08-20 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ya_market', '0002_alter_goods_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricesFBY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', models.PositiveIntegerField(max_length=6, verbose_name='Цена')),
                ('price_base', models.PositiveIntegerField(max_length=6, verbose_name='Цена до скидки')),
                ('updated', models.DateTimeField()),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_fby', to='ya_market.goods', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Товар пользователя')),
            ],
            options={
                'verbose_name': 'Цена товара',
                'verbose_name_plural': 'Цены товаров',
            },
        ),
        migrations.AddConstraint(
            model_name='pricesfby',
            constraint=models.UniqueConstraint(fields=('good_id',), name='unique goods'),
        ),
    ]
