# Generated by Django 3.2.20 on 2023-08-26 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ya_market', '0003_auto_20230820_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocksFBY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_good_stocks', models.PositiveIntegerField(blank=True, max_length=5, null=True, verbose_name='Остатки для продажи')),
                ('agency_commission', models.FloatField(blank=True, default=0.0, help_text='Прием и перечисление денег от покупателя (агентское вознаграждение)', max_length=8, null=True, verbose_name='Обработка платежа')),
                ('fee', models.FloatField(blank=True, default=0.0, help_text='Размещение товара на Маркете', max_length=8, null=True, verbose_name='Стоимость размещения')),
                ('fulfillment', models.FloatField(blank=True, default=0.0, help_text='Обработка товара на складе Маркета', max_length=8, null=True, verbose_name='Обработка на складе')),
                ('storage', models.FloatField(blank=True, default=0.0, help_text='Хранение товара на складе Маркета в течение суток', max_length=8, null=True, verbose_name='Стоимость хранения')),
                ('withdraw', models.FloatField(blank=True, default=0.0, help_text='Вывоз товара со склада Маркета', max_length=8, null=True, verbose_name='Возврат со склада')),
                ('surplus', models.FloatField(blank=True, default=0.0, help_text='Хранение излишков на складе Маркета', max_length=8, null=True, verbose_name='Хранение излишков')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_fby', to='ya_market.goods', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Остатки пользователя')),
            ],
            options={
                'verbose_name': 'Остаток товара и тарифы',
                'verbose_name_plural': 'Остатки товара и тарифы',
            },
        ),
        migrations.AddConstraint(
            model_name='stocksfby',
            constraint=models.UniqueConstraint(fields=('good_id',), name='unique goods in stocks'),
        ),
    ]
