# Generated by Django 3.2.20 on 2023-08-30 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ya_market', '0004_auto_20230826_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Валюта')),
                ('date', models.DateTimeField(verbose_name='Дата курса')),
                ('value', models.FloatField(max_length=5, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.CreateModel(
            name='UserCostPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.FloatField(help_text='Себестоимость 1 шт (без доставки)', max_length=6, verbose_name='Цена 1 шт')),
                ('buy_currency_rate', models.FloatField(help_text='Курс по которому купили', max_length=5, verbose_name='Курс покупки')),
                ('delivery_price', models.FloatField(blank=True, help_text='Стоимость доставки 1 шт', max_length=6, null=True, verbose_name='Доставка 1 шт')),
                ('delivery_currency_rate', models.FloatField(help_text='Курс по которому доставили', max_length=5, verbose_name='Курс доставки')),
                ('fulfilment_price', models.FloatField(blank=True, help_text='Стоимость складской обработки у продавца 1 шт', max_length=5, null=True, verbose_name='Складская обработка')),
                ('buy_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_currency', to='ya_market.currency', verbose_name='Валюта Закупа')),
                ('delivery_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_currency', to='ya_market.currency', verbose_name='Валюта доставки')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs_fby', to='ya_market.goods', verbose_name='Товара')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Себестоимость пользователя')),
            ],
            options={
                'verbose_name': 'Себестоимость товара',
                'verbose_name_plural': 'Себестоимости товаров',
            },
        ),
    ]
