# Generated by Django 3.2.20 on 2023-09-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_market', '0005_currency_usercostprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.AddConstraint(
            model_name='currencylist',
            constraint=models.UniqueConstraint(fields=('code',), name='unique code currency_list'),
        ),
    ]
