# Generated by Django 3.2.20 on 2023-09-05 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ya_market', '0006_auto_20230905_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercostprice',
            name='buy_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_currency', to='ya_market.currencylist', verbose_name='Валюта Закупа'),
        ),
        migrations.AlterField(
            model_name='usercostprice',
            name='delivery_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_currency', to='ya_market.currencylist', verbose_name='Валюта доставки'),
        ),
    ]
