# Generated by Django 3.2.20 on 2023-09-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_market', '0007_auto_20230905_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercostprice',
            name='buy_currency_rate',
            field=models.FloatField(blank=True, help_text='Курс по которому купили', max_length=5, null=True, verbose_name='Курс покупки'),
        ),
        migrations.AlterField(
            model_name='usercostprice',
            name='delivery_currency_rate',
            field=models.FloatField(blank=True, help_text='Курс по которому доставили', max_length=5, null=True, verbose_name='Курс доставки'),
        ),
    ]
