# Generated by Django 3.2.20 on 2023-09-10 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ya_market', '0008_auto_20230905_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeliveredOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10, verbose_name='Номер заказа')),
                ('creation_date', models.DateField(verbose_name='Дата заказа')),
                ('delivered_date', models.DateTimeField(verbose_name='Дата доставки')),
                ('good_sku', models.CharField(max_length=20, verbose_name='SKU товара')),
                ('items_count', models.IntegerField(verbose_name='Количество')),
                ('delivery_region', models.CharField(default='Нет указан', max_length=30, verbose_name='Регион доставки')),
                ('warehouse_name', models.CharField(default='Нет указан', max_length=30, verbose_name='Склад')),
                ('bid_fee', models.FloatField(default=0, verbose_name='Процент Буста')),
                ('payment_total', models.FloatField(verbose_name='Сумма заказа')),
                ('commission_delivery', models.FloatField(default=0, help_text='Стоимость доставки', verbose_name='Доставка')),
                ('commission_fee', models.FloatField(default=0, help_text='Все комиссии кроме доставки и рекламы', verbose_name='Комисся')),
                ('auction_total', models.FloatField(default=0, help_text='Стоимость буста продаж', verbose_name='Буст')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_good', to='ya_market.goods', verbose_name='Продажа товара')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_orders', to=settings.AUTH_USER_MODEL, verbose_name='Продажи Пользователя')),
            ],
            options={
                'verbose_name': 'Список заказов',
                'verbose_name_plural': 'Списки заказов',
            },
        ),
        migrations.AddConstraint(
            model_name='userdeliveredorders',
            constraint=models.UniqueConstraint(fields=('order_id',), name='unique order_id'),
        ),
    ]
