# Generated by Django 3.2.20 on 2023-09-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_market', '0009_auto_20230910_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeliveredorders',
            name='auction_total',
            field=models.FloatField(default=0, help_text='Стоимость буста продаж', null=True, verbose_name='Буст'),
        ),
        migrations.AlterField(
            model_name='userdeliveredorders',
            name='bid_fee',
            field=models.FloatField(default=0, null=True, verbose_name='Процент Буста'),
        ),
    ]
