# Generated by Django 3.2.20 on 2023-09-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_market', '0010_auto_20230910_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeliveredorders',
            name='delivery_region',
            field=models.CharField(default='Нет указан', max_length=50, verbose_name='Регион доставки'),
        ),
    ]
