# Generated by Django 3.2.20 on 2023-07-29 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.IntegerField(max_length=10, verbose_name='Цена')),
                ('days_amount', models.PositiveIntegerField(max_length=4, verbose_name='Кол-во дней')),
            ],
            options={
                'verbose_name': 'План подписки',
                'verbose_name_plural': 'Планы подписки',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserYaKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FBY_campaign_id', models.BigIntegerField(blank=True, max_length=8, null=True, verbose_name='Id FBY кампании Yandex')),
                ('FBS_campaign_id', models.BigIntegerField(blank=True, max_length=8, null=True, verbose_name='Id FBS кампании Yandex')),
                ('DBS_campaign_id', models.BigIntegerField(blank=True, max_length=8, null=True, verbose_name='Id DBS кампании Yandex')),
                ('ya_oauth_token', models.CharField(max_length=100, verbose_name='OAuth токен Яндекса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Яндекс ключи пользователя',
                'verbose_name_plural': 'Яндекс ключи пользователей',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name='Дата старта плана')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания плана')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subscription', verbose_name='План подписки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подписчик на план')),
            ],
            options={
                'verbose_name': 'План подписки пользователя',
                'verbose_name_plural': 'Планы подписки пользователей',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='useryakeys',
            constraint=models.UniqueConstraint(fields=('ya_oauth_token',), name='unique oauth'),
        ),
    ]
