# Generated by Django 3.2.20 on 2023-08-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useryakeys_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useryakeys',
            name='business_id',
            field=models.CharField(blank=True, max_length=8, verbose_name='BusinessId кабинета'),
        ),
    ]
